### ISSUE TITLE
Plaintext-Access Tokens

### ISSUE THREAD

**Issue by AOrps** [jadon-gro/API-Learning#1]
Your token is in plaintext: https://github.com/jadon-gro/API-Learning/blob/master/weather.py#L9

**Comment by jadon-gro** [comment]
You can still see the error in previous commits which is fine. People can abuse my free key if they want. I updated the code so now it reads from a .env file :)

**Comment by AOrps** [comment]
Btw still in your commit history, but yee that's a whole other can of worms.

Ofc!
